CREATE DATABASE EX_1_3;

USE EX_1_3;

CREATE TABLE Clinica
(
IdClinica INT PRIMARY KEY IDENTITY,
NomeCLinica VARCHAR(50),
Endereco VARCHAR(100 ) NOT NULL
)

CREATE TABLE TipoPet
(
IdTipoPet INT PRIMARY KEY IDENTITY,
NomeTipo VARCHAR(50)
)

CREATE TABLE Raça
(
IdRaça INT PRIMARY KEY IDENTITY,
NomeRaça VARCHAR(50)
)


CREATE TABLE Dono
(
IdDono INT PRIMARY KEY IDENTITY,
NomeDono VARCHAR(100) NOT NULL
)


CREATE TABLE Veterinarios
(
IdVeterinarios INT PRIMARY KEY IDENTITY,
IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica) NOT NULL,
NomeVet VARCHAR(100) NOT NULL, 
CMRV VARCHAR(11) NOT NULL
)

CREATE TABLE Pets
(
IdPets INT PRIMARY KEY IDENTITY,
IdTipoPet INT FOREIGN KEY REFERENCES TipoPet(IdTipoPet) NOT NULL,
IdRaça INT FOREIGN KEY REFERENCES Raça(IdRaça) NOT NULL,
IdDono INT FOREIGN KEY REFERENCES Dono(IdDono) NOT NULL,
NomePet VARCHAR(100) NOT NULL,
DataNascimento DATE NOT NULL
)

CREATE TABLE Atendimento
(
IdAtendimento INT PRIMARY KEY  IDENTITY,
IdVeterinarios INT FOREIGN KEY REFERENCES Veterinarios(IdVeterinarios),
IdPets INT FOREIGN KEY REFERENCES Pets(IdPets),
Descriçao VARCHAR(240) NOT NULL,
DataAtentimento DATE NOT NULL
)


