--DDL
CREATE DATABASE Ex_1_1;

USE Ex_1_1;

CREATE TABLE Pessoa
(
IdPessoa INT PRIMARY KEY IDENTITY,
Nome VARCHAR(50) NOT NULL,
CNH CHAR(11) NOT NULL,
)

CREATE TABLE Email
(
IdEmail INT PRIMARY KEY IDENTITY,
IdPessoa INT FOREIGN KEY REFERENCES Pessoa(IdPessoa),
Endereço VARCHAR(50) NOT NULL,
)

CREATE TABLE Telefone
(
IdTelefone INT PRIMARY KEY IDENTITY,
IdPessoa INT FOREIGN KEY REFERENCES Pessoa(IdPessoa),
Numero VARCHAR(30) NOT NULL,
)